// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC1eory_0jnHti3Kz06Sf1MCOgk3EOsYC4',
    appId: '1:1038214637528:web:7a91f8afb8c7fe7c7374ad',
    messagingSenderId: '1038214637528',
    projectId: 'quizapp-e7f6f',
    authDomain: 'quizapp-e7f6f.firebaseapp.com',
    storageBucket: 'quizapp-e7f6f.firebasestorage.app',
    measurementId: 'G-KYYBPBYZBX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDHz2M-e0nbR9YQxFCqIPotF_2s-mUI7a0',
    appId: '1:1038214637528:android:a2b4a28338a8dd027374ad',
    messagingSenderId: '1038214637528',
    projectId: 'quizapp-e7f6f',
    storageBucket: 'quizapp-e7f6f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCOgYldATqgjI0P4nEo5UThhUszz3Xuch8',
    appId: '1:1038214637528:ios:7ea388081107f4b27374ad',
    messagingSenderId: '1038214637528',
    projectId: 'quizapp-e7f6f',
    storageBucket: 'quizapp-e7f6f.firebasestorage.app',
    iosBundleId: 'com.example.quizApp',
  );
}